### ISSUE TITLE
Don't crash on FDB.start, use error codes

### ISSUE THREAD

**Issue by fire** [ananthakumaran/fdb#12]
Is it possible to not crash on FBD.start(600)?

We can use the standard error codes for :ok and {:error, exception}.

**Comment by ananthakumaran** [comment]
Sorry, I don't understand the context. Could you please explain a bit more and [readme](https://github.com/ananthakumaran/fdb#error-handling) explains why exception is used everywhere instead of standard error codes

**Comment by fire** [comment]
Do you have an example of how to start Elixir FDB multiple time in a thread pool if `:ok = FDB.start(600)` will cause an exception on the second initialization?

**Comment by ananthakumaran** [comment]
> The goal is to use more than one core.

This is not currently possible with any of the foundationdb clients (unless you start multiple os process) because of the way the foundationdb c api works. foundationdb c api uses event loop internally and won't use more than one core and we can't start more than one of them.

Practically speaking, because of the use of async io, it rarely becomes a problem. You don't need to manage db connection pools like we do for other databases normally. The foundationdb c api takes care of networking part and read/writes from elixir processes won't block each other. Try to benchmark you case and see if it's a problem.

**Comment by fire** [comment]
This is what I have currently. I'm trying to match the numbers of the fdb documentation page and failing.

![Screen Shot 2019-06-29 at 10 37 36 AM](https://user-images.githubusercontent.com/32321/60387563-ee29e280-9a59-11e9-9d47-0ccc45f835db.png)

https://apple.github.io/foundationdb/benchmarking.html

Using https://github.com/fire/nebulex_fdb_adapter which is my custom written FDB driver.

To test it I would use `mix run benchmarks/benchmark.exs` and mix test.

I put in the poolboy connection pool because when I max out parallel requests it causes the entire system to halt.

It seems closer to:

```Loop for 1 minute:
    Start a transaction
    Write 10 random keys to new random values
    Commit

Result: 8,650 writes/second
```

Rather than.

```
Start 100 parallel clients, each doing:
    Loop for 1 minute:
        Start a transaction
        Write 10 random keys to new random values
        Commit

Result: 46,000 writes/second
```

**Comment by fire** [comment]
Web research says that it might be possible to run multiple subprocesses of the client.

```
Nifty starts a node in an external process, which handles the NIF module.
# https://parapluu.github.io/nifty/tutorial5/
```

**Comment by ananthakumaran** [comment]
I am assuming you have seen the benchmark https://github.com/ananthakumaran/fdb/blob/master/BENCHMARK.md and the script https://github.com/ananthakumaran/fdb/blob/master/bench.exs

> I put in the poolboy connection pool because when I max out parallel requests it causes the entire system to halt.

Could you share the numbers (parallelism) you are testing with? I have tried with 100 and it was working without issue.

**Comment by fire** [comment]
This is using your benchmark script but upgraded to benchee 1.0.

https://gist.github.com/fire/bb8286118a851832c194f85070bd6438

**Comment by ananthakumaran** [comment]
There are two things to note,
1) benchee reports ips per process, so if we set parallel to 10, we have to multiply by 10
2) apple benchmark consider operating on single key as a single op. in our case, `read  10 op` would then be considered as 10 ops. So we have scale the numbers by another 10.

This is the reason I have used a custom formatter with benchee.

Although I haven't done extensive performance test, the client is at least able to perform in the order of 100k ops per second. I don't have access to bigger cluster to test further. But I am definitely interested in fixing any perf issues.

What kind of ops per second are you expecting?

**Comment by fire** [comment]
I was confused why the benchee numbers were different. 

Here's an updated version of the benchmark script. It is updated to benchee 1.0.

https://gist.github.com/fire/16172ec33bed7fb72b9122ffa853673b

**Comment by fire** [comment]
Using the revised benchmark I was able to get ~100k.

Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
Number of Available Cores: 6
Available memory: 16 GB
Elixir 1.9.0
Erlang 22.0.4

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 0 ns
parallel: 100
inputs: none specified
Estimated total run time: 28 s
```
Benchmarking read   1 op...
Benchmarking read  10 op...
Benchmarking write  1 op...
Benchmarking write 10 op...
           name    concurrency     ops/s   average ms    max ms    min ms   deviation
    read   1 op            100     43028     2324.053   14006.0     917.0     ±48.74%
    read  10 op            100    112986     8850.653   28267.0    5523.0     ±13.41%
    write  1 op            100      7812    12800.731   62021.0    7742.0      ±40.5%
    write 10 op            100     36819    27159.622   71417.0   11397.0     ±35.05%
```

Also, the fdb process was only at 50%.

**Comment by fire** [comment]
If you're curious, I got these numbers.

```
$ mix run benchmarks/benchmark.exs
Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
Number of Available Cores: 6
Available memory: 16 GB
Elixir 1.9.0
Erlang 22.0.4

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 0 ns
parallel: 100
inputs: Distributed Cache
Estimated total run time: 1.20 min

Benchmarking add with input Distributed Cache...
Benchmarking delete with input Distributed Cache...
Benchmarking get with input Distributed Cache...
Benchmarking has_key? with input Distributed Cache...
Benchmarking set with input Distributed Cache...
Benchmarking take with input Distributed Cache...
           name    concurrency     ops/s   average ms    max ms    min ms   deviation
            get            100     50209     1991.673   12788.0     912.0     ±17.85%
       has_key?            100     48016     2082.602   11238.0    1037.0     ±20.56%
            add            100      8098    12348.318   40229.0    7132.0     ±21.63%
         delete            100      7877    12694.729   51538.0    7106.0     ±37.54%
            set            100      7210     13868.04   98524.0    7816.0     ±51.14%
           take            100      6069     16476.15  154216.0    8105.0     ±82.99%
```

**Comment by fire** [comment]
Hm, these numbers are a bit artificial. I want to try some end to end tests with https://www.techempower.com/benchmarks/. Benchee isn't easy to use.

**Comment by fire** [comment]
I was expecting to load the fdb process to 100% and / or load 4 fdb processes at somewhere near 100k per server fdb process.

**Comment by ananthakumaran** [comment]
Recently a tool called [mako](https://github.com/apple/foundationdb/pull/1586) got merged. I just run it on my local machine
```bash
# setup
mako --cluster /usr/local/etc/foundationdb/fdb.cluster --mode clean
mako --cluster /usr/local/etc/foundationdb/fdb.cluster --mode build --rows 1000000 --procs 4

mako --cluster /usr/local/etc/foundationdb/fdb.cluster --mode run --rows 1000000 --procs 1 --threads 50 --transaction "g10" --seconds 10 --verbose 1
```

```
                      GET          TPS  Conflicts/s
============ ============ ============ ============
         OPS         5180      4998.75         0.00
         OPS        80490      8043.76         0.00
         OPS        82326      8226.77         0.00
         OPS        81836      8182.50         0.00
         OPS        79755      7970.45         0.00
         OPS        80842      8078.53         0.00
         OPS        81518      8150.46         0.00
         OPS        81051      8103.13         0.00
         OPS        77900      7772.64         0.00
         OPS        70807      7058.61         0.00
         OPS        79412      7940.51         0.00

====== Total Duration 10.208 sec ======

Total Processes:         1
Total Threads:          50
Target TPS:              0
Total Xacts:         80451
Total Conflicts:         0
Total Errors:            0
Overall TPS:          7881

                      GET          TPS  Conflicts/s
============ ============ ============ ============
Total OPS          804510      7881.09         0.00
Errors                  0
Lat Min (us)          355          N/A
Lat Avg (us)         1104          N/A
Lat Max (us)         4813          N/A
```

The OPS I get in mako & fdb is more or less around the same range (~80k).

At this point, either the client (fdb) is bottleneck or the server is fully saturated. But given that mako also gives the same kind of TPS, I am more inclined to believe the server is saturated. As you mentioned, the fdb server seems to go upto at 70% cpu usage, not sure if it's hitting some kind of IO bottleneck at that level.

Anyways, if you have access to bigger cluster, I would be very much interested in the results of fdb vs mako.
