### ISSUE TITLE
Class scheduling tutorial

### ISSUE THREAD

**Issue by ruslandoga** [ananthakumaran/fdb#17]
Hi!

I'm working through a class scheduling tutorial and I'm wondering if there is an easy way to open subspaces like in the [python example:](https://apple.github.io/foundationdb/class-scheduling.html#directories-and-subspaces)

```python
scheduling = fdb.directory.create_or_open(db, ('scheduling',))
course = scheduling['class']
attends = scheduling['attends']
```

Right now I'm doing the following:

1. storing the directory in `persistent_term`:

```elixir
  scheduling =
      Database.transact(db, fn t ->
        Directory.create_or_open(Directory.new(), t, ["scheduling"])
      end)

    :persistent_term.put(:fdb_dir, scheduling)
```
```elixir
  defp fdb_dir do
    :persistent_term.get(:fdb_dir)
  end
```

2. creating custom `coder_` functions for the coders:

```elixir
  # ("class", class) -> seats
  defp class_coder(dir \\ fdb_dir()) do
    key =
      Coder.Subspace.concat(
        Coder.Subspace.new(dir),
        Coder.Subspace.new("class", Coder.ByteString.new())
      )

    val = Coder.Integer.new()
    Transaction.Coder.new(key, val)
  end
```

3. and calling these functions inside the "domain" functions

```elixir
  # @fdb.transactional
  # def add_class(tr, c):
  #     tr[course.pack((c,))] = fdb.tuple.pack((100,))
  def add_class(tr, c) do
    Transaction.set(tr, c, 100, %{coder: class_coder()})
  end
```

I wonder if there is a simpler way to pass the directory in these functions if there are several coders can be used in a single transaction like in the tutorial?

**Comment by ruslandoga** [comment]
Also I think I didn't something wrong in my approach since I'm getting `"class"` back in the range:

```
  def available_classes(tr) do
    tr
    |> Transaction.get_range_stream(KeySelectorRange.starts_with(""))
    |> Enum.map(fn {k, v} -> k end)
  end

  # returns something like `<<20, 99, 108, 97, 115, 115, 1, 57, 58, 48, 48, 32, 109, 117, 115, 105, 99, 32, 105, 110, 116, 114, 111, 0>>`
```

**Comment by ruslandoga** [comment]
I wonder if a function that takes a list would make sense to create subspaces:

```elixir
                         # dir # prefix  # class name
subspace = Subspace.new([dir,  "class",  ByteString.new()])
```

**Comment by ananthakumaran** [comment]
Agree, compared to python it's quite verbose. There are multiple places where syntactic sugar could be added to make code more readable. But, at this moment, I am not sure if anybody actually uses the library. I would be more interested in fixing bugs or adding things that are not possible to do in this library compared to other bindings.

**Comment by ruslandoga** [comment]
Fair enough. I guess I can abstract some calls in my app code.
