### ISSUE TITLE
Ranges without explicit end

### ISSUE THREAD

**Issue by WolfDan** [ananthakumaran/fdb#9]
Hey!

This is the same question as [this forum post](https://forums.foundationdb.org/t/ranges-without-explicit-end-go/773) but for this elixir library

I wanted to do the same as a `>`,  `>=`, `<=` operations, I need to give the `begin` parameter to the tuple which is the number you need to compare, but in case of the `end` parameter what data I should give in order to get all the keys with the given condition? 

In the forum post they mention the `FDBRangeKeys()` Go function and get the last item of the tuple as the `end` parameter, but I did not find anything similar in the elixir library, is it implemented? 

Thank you!

**Comment by ananthakumaran** [comment]
Yes, this is already available. Checkout [KeySelector](https://hexdocs.pm/fdb/FDB.KeySelector.html#content) docs, specially the `prefix` option. I have also added some tests https://github.com/ananthakumaran/fdb/blob/master/test/tutorial/range_test.exs where you can find examples.

**Comment by WolfDan** [comment]
Perfect!

Exactly what I was looking for, thank you so much
